### ISSUE TITLE
Scan Not Working – `fernet.InvalidToken` Error

### ISSUE THREAD

**Issue by BRVN01** [internetstandards/Internet.nl-dashboard#591]
Hi,

I'm running the **dashboard** on one server and **Internet.nl** on another. The Internet.nl instance is working fine, and the API responds correctly when accessed via the Linux CLI.

However, when I attempt to run a **scan** through the dashboard, nothing happens in the browser. I only see the error in the Docker logs:

```
backend-1           | 2025-06-17 17:20:52	ERROR    - Internal Server Error: /data/urllist/scan_now/
backend-1           | Traceback (most recent call last):
backend-1           |   File "/pyenv/lib/python3.10/site-packages/cryptography/fernet.py", line 130, in _verify_signature
backend-1           |     h.verify(data[-32:])
backend-1           | cryptography.exceptions.InvalidSignature: Signature did not match digest.
backend-1           | 
backend-1           | During handling of the above exception, another exception occurred:
backend-1           | 
backend-1           | Traceback (most recent call last):
backend-1           |   File "/pyenv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
backend-1           |     response = get_response(request)
backend-1           |   File "/pyenv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
backend-1           |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
backend-1           |   File "/pyenv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
backend-1           |     return view_func(request, *args, **kwargs)
backend-1           |   File "/source/dashboard/internet_nl_dashboard/views/domains.py", line 148, in scan_now_
backend-1           |     return JsonResponse(scan_now(get_account(request), get_json_body(request)))
backend-1           |   File "/source/dashboard/internet_nl_dashboard/logic/domains.py", line 193, in scan_now
backend-1           |     if not account.connect_to_internet_nl_api(account.internet_nl_api_username, account.decrypt_password()):
backend-1           |   File "/source/dashboard/internet_nl_dashboard/models.py", line 92, in decrypt_password
backend-1           |     return fernet.decrypt(bytes(self.internet_nl_api_password[2:-1], encoding="UTF-8")).decode("utf-8")
backend-1           |   File "/pyenv/lib/python3.10/site-packages/cryptography/fernet.py", line 89, in decrypt
backend-1           |     return self._decrypt_data(data, timestamp, time_info)
backend-1           |   File "/pyenv/lib/python3.10/site-packages/cryptography/fernet.py", line 148, in _decrypt_data
backend-1           |     self._verify_signature(data)
backend-1           |   File "/pyenv/lib/python3.10/site-packages/cryptography/fernet.py", line 132, in _verify_signature
backend-1           |     raise InvalidToken
backend-1           | cryptography.fernet.InvalidToken
```

This seems to be related to a `fernet.InvalidToken` error during password decryption, as shown in the traceback.

I have set the key in my .env file, but I'm not sure what this error means.

```
cat docker-compose.yml
services:
  db:
    image: postgres:11
    environment:
      POSTGRES_DB: dashboard
      POSTGRES_USER: dashboard
      POSTGRES_PASSWORD: dashboard
  broker:
    image: redis
  frontend:
    build: .
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: 'TkzHMDld7XOqZwr9J-_nmhSAXslUFlIZfKbzv3f9QLE='
      FIELD_ENCRYPTION_KEY: 'irJMSaJ-tzhjn3RbYti__bcTL6Yzbg-0AlZib5VwJeU='
      DJANGO_DATABASE: production
      DB_ENGINE: postgresql_psycopg2
      DB_HOST: db
      BROKER: redis://broker:6379/0
  migrate:
    build: .
    image: internetstandards/dashboard
    restart: on-failure
    environment:
      SECRET_KEY: 'TkzHMDld7XOqZwr9J-_nmhSAXslUFlIZfKbzv3f9QLE='
      FIELD_ENCRYPTION_KEY: 'irJMSaJ-tzhjn3RbYti__bcTL6Yzbg-0AlZib5VwJeU='
      DJANGO_DATABASE: production
      DB_ENGINE: postgresql_psycopg2
      DB_HOST: db
    command: migrate
```

Can you help me resolve this issue?

**OS:** Ubuntu 22.04 LTS
**Dashboard Version:** 5.0.0
**Internet nl Version:** 1.9.3
